pipeline {
    agent {
        label 'docker'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Build/compile application'
                sh 'docker build -t adhithia21/goapp:${BUILD_NUMBER} .'
    
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'docker login --username=$USER --password=$PASS'
                }

                sh 'docker push adhithia21/goapp:${BUILD_NUMBER}'
                
            }
        }
        stage('Test') {
            steps {
                echo 'Test run application'
                sh 'docker run -d --name goapp-run-test -p 8080:8080 adhithia21/goapp:${BUILD_NUMBER}'
                sh 'curl http://localhost:8080/api'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy to server'
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}

