pipeline {
    agent {
        label 'docker'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Build/compile application'
                sh 'docker build -t adhithia21/goapp:${BUILD_NUMBER} .'
    
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'docker login --username=$USER --password=$PASS'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Test run application'
                sh 'docker run -d --name goapp-run-test -p 8080:8080 adhithia21/goapp:${BUILD_NUMBER}'
                sh 'curl http://localhost:8080/api'
            }
            post {
                success {
                    sh 'docker push adhithia21/goapp:${BUILD_NUMBER}'
                }
                cleanup {
                    sh 'docker rm -f goapp-run-test'
                    sh 'docker image rm adhithia21/goapp:${BUILD_NUMBER}'
                }
            }
        }
        stage('Deploy') {
            environment {
                KUBECONFIG = credentials('kubeconfig-jenkins')
            }
            steps {
                echo 'Deploy to server'
                sh 'kubectl get nodes'
                sh 'kubectl apply -f .devops/kube/Deployment.yaml'
                sh 'kubectl apply -f .devops/kube/Service.yaml'
            }
        }
    }
    post { 
        always { 
            cleanWs()
        }
    }
}

