apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: adhithia21/goapp:CHANGE_TAG
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
